name: Monthly Price Analysis Report

on:
  schedule:
    # Run on the 1st of every month at 10:00 AM UTC
    - cron: '0 10 1 * *'
    
    # Alternative: Run quarterly (every 3 months)
    # - cron: '0 10 1 1,4,7,10 *'  # Jan 1, Apr 1, Jul 1, Oct 1
    
  workflow_dispatch:  # Allow manual trigger

jobs:
  price-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate price analysis report
      env:
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: |
        echo "📊 Generating comprehensive price analysis report..."
        python price_analysis_reporter.py
        echo "✅ Analysis report generated and emailed!"
    
    - name: Upload analysis report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: price-analysis-report-${{ github.run_number }}
        path: |
          price_analysis_*.txt
          price_analysis_*.html
        retention-days: 90